### ISSUE TITLE
add JNA .dlls

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/cryptomator-win#10]
We should include (and sign) `jnidispatch.dll` and any other potentially needed libs and set the `jna.boot.library.path` system property accordingly.

This prevents JNA from extracting unsigned native libraries from jars to a temp directory.

See also: https://github.com/cryptomator/cryptomator/issues/736

**Comment by overheadhunter** [comment]
While this seems to work for now (maybe @Bodup can verify it is working with 1.4.0-rc1?), we should still explicitly set 

* `jna.boot.library.name` to `jnidispatch` and
* `jna.boot.library.path` to `.`

via ant-kit's `fx:property` in the `build.xml`.

See https://stackoverflow.com/a/43820391/4014509 for details.

**Comment by jasperweiss** [comment]
Can confirm that it's working now 👍
