### ISSUE TITLE
Dokany silent install possible (Chocolatey)?

### ISSUE THREAD

**Issue by RiseT** [cryptomator/cryptomator-win#11]
## Basic Info

I'm using Windows / macOS / Linux / … in version:
Win 10

I'm running Cryptomator in version:
1.4

## Description

It seems like Dokany currently bypasses the silent install args during installation which leads to failed automated testing of the Chocolatey package:

https://chocolatey.org/packages/cryptomator/1.4.0
(Note the failed automated testing and the comment by the package maintainer in the comment section)

Is there something that can be done about this on your side?

## Attachments (optional)
n/a

**Comment by RiseT** [comment]
I'm no chocolatey expert either, but I do know for a fact that it does support dependencies.

**Comment by overheadhunter** [comment]
Then this should be the easiest and most reliable solution. 🙂 

Edit: Also it allows chocolatey users to uninstall Dokany the same way it got onto the system. Therefore I consider it more transparent than any implicitly invoked sub-installer.

**Comment by RiseT** [comment]
Thanks! So I'm closing this for the time being. I've pointed the package maintainer to this thread.

**Comment by RiseT** [comment]
@overheadhunter 
The dependency been implemented into the chocolatey package now.

I wonder, though, what the difference between

- [DokanSetup_redist.exe](https://github.com/dokan-dev/dokany/releases/download/v1.2.0.1000/DokanSetup_redist.exe) (much larger file size) and
- [Dokan_x64.msi](https://github.com/dokan-dev/dokany/releases/download/v1.2.0.1000/Dokan_x64.msi) is.

For both there are choco packages available:

- https://chocolatey.org/packages/dokany-redistributable
- https://chocolatey.org/packages/dokany

And which one is more appropriate regarding a dependeny for Cryptomator?

**Comment by overheadhunter** [comment]
The msi package only installs Dokan itself, while the redist installer [also includes Visual C++ Redistributable](https://github.com/dokan-dev/dokany/blob/6424efd09d8efd5f1ae6622a6b4ef9be27d25153/dokan_wix/Bootstrapper/Bundle.wxs#L64-L123) for both, x86 and x64.

Since we're already using Chocolatey for dependency management, I'd suggest to use the smaller msi package.

Btw I think the Dokany package should update its dependencies, too:
* I think `<dependency id="dotnet4.0" />` can be removed (see dokan-dev/dokany#710)
* `<dependency id="vcredist2015" />` should be updated to `vcredist2017`

@Liryna is this assumption correct?

**Comment by Liryna** [comment]
Hi @overheadhunter ,

You are exactly right. The installer no longer needs dotnet and vcredist used is 2017 👍

**Comment by bcurran3** [comment]
Hi @Liryna,

I've updated the Chocolatey package for the next release. I've removed the dotnet4.0 dependency and changed the vcredist2015 dependency to vcredist2017.

Is kb2999226 still required?

**Comment by Liryna** [comment]
kb2999226 is still required unfortunately yes. We tried to remove it when moving for vc2017 but found out that still needed for vc2017 install 😢 
https://github.com/dokan-dev/dokany/issues/628

**Comment by bcurran3** [comment]
Thanks for the verification. I'll keep it in.

**Comment by Hariama** [comment]
Hi all,

@RiseT: Thank you for notifying me for the update, and for working out with @overheadhunter that adding the dependency was the right move. As the .msi file is much smaller, I'll keep the dependency as-is right now. Sorry that it took so long to update, I tried to make it work within the automated verification process, but with the dokany-dependency this was no longer possible.

**Comment by bcurran3** [comment]
> ...but with the dokany-dependency this was no longer possible.

Actually because of the kb2999226 dependency. :)
