### ISSUE TITLE
Migrate to Inno Setup 6

### ISSUE THREAD

**Issue by infeo** [cryptomator/cryptomator-win#14]
Recently InnoSetup 6.0.2 was [released](http://www.jrsoftware.org/isdlold.php#6). We should check for new features and update our build script to use them.

**Comment by overheadhunter** [comment]
Done in d3eda6a, however we're deliberately sticking with the ["classic" WizardStyle](https://github.com/cryptomator/cryptomator-win/blob/d3eda6ae8036d629b7783cfb3b98c1ad76558446/resources/innosetup/setup.iss#L40) until we release Cryptomator 1.5.0.
