### ISSUE TITLE
Dokany refuses to install but Visual C++ Runtime is present

### ISSUE THREAD

**Issue by edgarrc** [cryptomator/cryptomator-win#15]
### **Basic info**

- Windows 10
- Cryptomator-1.4.10-x64
- Visual C++ Runtime versions present, before started the instalation:

![image](https://user-images.githubusercontent.com/1680085/57668684-7ead8000-75de-11e9-82cc-069e25e50824.png)

### **Issue**

The installer shows a warning saying that Dokany will not be installed because Visual C++ Runtime is not present, but it is present. Looks like the dependency version is just referencing a specific and old one.

The old version of Visual C++ Runtime. linked on Crytomato's download url, can't be insalled if you already have a most recent version installed.

### **Related** 

- #756
- #12

**Comment by overheadhunter** [comment]
I assume you get this warning from the Dokany installer, not from the Cryptomator installer. I.e. _after_ Cryptomator launches the "subinstaller"? In this case it might be worth reporting this issue to [dokan-dev/dokany](https://github.com/dokan-dev/dokany).

**Comment by edgarrc** [comment]
@overheadhunter I was not sure about this because of this commit:

https://github.com/cryptomator/cryptomator-win/commit/24d336b7ecfa9b521341c6b0c4fe6ac42dd7af68

Looks like this verification step is done on Cryptomator setup process, calling this function DokanDependencyCheck

This function uses the registry path:

`RegVcRedistKey = 'SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0\VC\Runtimes\x64';`

Which I have on registry. But requires: 

`Result := (major >= 14) and (minor >= 11) and (build >= 25325)`

Which I don't have installed exactly like is required, despite of having a most recent version installed:

![image](https://user-images.githubusercontent.com/1680085/57692941-678e8280-761e-11e9-9615-465c333d1a35.png)

While searching about this, I found a bug on VC++ runtime installer:

https://developercommunity.visualstudio.com/content/problem/332815/visual-c-redistributable-2017-install-removes-visu.html

After Joseph Scarpato, answer, I don't think Microsoft will fix this. But he is suggesting as a workaround calling an repair on VC++ setup. According to this post, the repair procedure will fix this registry setting correctly.

I will try to manually repair this VC++ setup and try again.

**Comment by overheadhunter** [comment]
Interesting... there might be others having the same problem, so we should consider any other way of checking the VC++ version, as we can not ask everyone to manually fix their registry...

**Comment by edgarrc** [comment]
After repair, this is what my registry looks like:

![image](https://user-images.githubusercontent.com/1680085/57695148-dfab7700-7623-11e9-8bd5-13898bda8283.png)

So this function will not fail anymore. 

Maybe the wmic command can be used (it requires elevated privileges to be run), this command will list all programs installed. 

```
C:\WINDOWS\system32>wmic
wmic:root\cli>/output:C:\Temp\InstalledPrograms.txt product get name,version
wmic:root\cli>
```

**Comment by ifrh** [comment]
Well, 
On Windows 8.1 (64bit) I have installed multiple MSVC redist (and multiple Java versions) and in Cryptomator 1.4.10 I can choose Dokany.
But updating Cryptomator from 1.4.2-x64 to 1.4.10-x64 an Windows 10 (64bit) 
with also having multiple MSVC-redist 
![grafik](https://user-images.githubusercontent.com/3845055/58435666-d6a9b380-80c1-11e9-8dab-3d1d86311694.png)
I cannot choose Docany inside Cryptomator - well there is a Java 8 in my PATH-variable.

**Comment by ifrh** [comment]
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads

>  Download the Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019. The following updates are the latest supported Visual C++ redistributable packages for Visual Studio 2015, 2017 and 2019. Included is a baseline version of the Universal C Runtime see MSDN for details.
> 
>     x86: [vc_redist.x86.exe](https://aka.ms/vs/16/release/vc_redist.x86.exe)
> 
>     x64: [vc_redist.x64.exe](https://aka.ms/vs/16/release/vc_redist.x64.exe)
> 
>     ARM64: [vc_redist.arm64.exe](https://aka.ms/vs/16/release/VC_redist.arm64.exe)
> 
> Note Visual C++ 2015, 2017 and 2019 all share the same redistributable files.
> 
> For example, installing the Visual C++ 2019 redistributable will affect programs built with Visual C++ 2015 and 2017 also. However, installing the Visual C++ 2015 redistributable will not replace the newer versions of the files installed by the Visual C++ 2017 and 2019 redistributables.
> 
> This is different from all previous Visual C++ versions, as they each had their own distinct runtime files, not shared with other versions.

After installing "Visual C++ 2015, 2017 ,2019" redist from above, I could reinstall Cryptomator with enabled Dokany.
![grafik](https://user-images.githubusercontent.com/3845055/58437873-360cc100-80cc-11e9-8a02-543d55c52a1a.png)

![grafik](https://user-images.githubusercontent.com/3845055/58438029-00b4a300-80cd-11e9-963f-fde51c955cc0.png)

The solution, in my opinion, is to update your the URL for current MSVC-redist on your webpage:
![grafik](https://user-images.githubusercontent.com/3845055/58438235-20989680-80ce-11e9-9196-9f1b6f126412.png)
