### ISSUE TITLE
Cryptomator setup changes FileSizeLimitInBytes even if WebDAV is unchecked

### ISSUE THREAD

**Issue by hippotastic** [cryptomator/cryptomator-win#22]
### Description

When installing Cryptomator on Windows and unchecking WebDAV support, setup still changes the `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WebClient\Parameters` value `FileSizeLimitInBytes` to MAX_DWORD (0xffffffff).

This is supposed to be a fix for working with files above 50 MB over WebDAV (50 MB is the default value for this limit) and only needed when using WebDAV.

If I do not want to use WebDAV and therefore uncheck it during setup, Cryptomator should not touch WebDAV-related registry settings.

### System Setup

* Operating system and version: Windows 10.0.18362.356
* Cryptomator version: 1.4.15
* Drive: Dokany (WebDAV intentionally unchecked during setup)

### Steps to Reproduce

1. Launch the installer
2. Uncheck WebDAV
3. Finish the installation
4. Open regedit
5. Navigate to `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WebClient\Parameters`
6. Check the value of `FileSizeLimitInBytes`

#### Expected Behavior

The FileSizeLimitInBytes should still have the Windows default value of 50000000 (0x2faf080).

#### Actual Behavior

The FileSizeLimitInBytes is changed to MAX_DWORD (0xffffffff).

#### Reproducibility

Always

**Comment by overheadhunter** [comment]
Adding [`Components: webdav`](http://www.jrsoftware.org/ishelp/index.php?topic=componentssection) to this line should fix it:

https://github.com/cryptomator/cryptomator-win/blob/9067840e5f7e66cdb13112c4ef419bb8abcd7b4b/resources/innosetup/setup.iss#L53
