### ISSUE TITLE
Silent Installation ohne Dokan Treiber nicht möglich

### ISSUE THREAD

**Issue by SoftwareITEM** [cryptomator/cryptomator-win#31]
Hallo Cryptomator-Team,
wir haben bisher den Cryptomator 1.4.x automatisiert ohne WebDav und ohne Dokan Treiber verteilt.
Seit der V1.5.x ist es nicht mehr möglich eine silent Installation ohne Dokan Treiber durchzuführen.
Der Installationsparameter SetupType=custom Components=main startet trotzdem die Dokan Installation. Ein Bug oder ein Feature?
Danke

**Comment by overheadhunter** [comment]
_Sollte_ nicht so sein: 🤔 

https://github.com/cryptomator/cryptomator-win/blob/49ad465ba0cf4238174a383525eed4c1aa176ac9/resources/innosetup/setup.iss#L73

**Comment by SoftwareITEM** [comment]
Ist aber so... 
Machen wir etwas falsch? Was wäre die Lösung? Wir benötigen wirklich nur die Main-Komponente.

Das ist der Aufruf der exe:
Cryptomator-1.5.4-x64.exe /FORCEINSTALL /SILENT /SP- /SUPPRESSMSGBOXES  /NOCANCEL /NORESTART /LOADINF=Comp.inf

Der Inhalt der Comp.inf:
[Setup]
Lang=en
Dir=%ProgramFilesDir%\Cryptomator
Group=Cryptomator
NoIcons=0
SetupType=custom
Components=main
Tasks=

**Comment by SoftwareITEM** [comment]
Können wir hier noch eine Lösung erwarten?
Viele Grüße

**Comment by overheadhunter** [comment]
Nein, ich wüsste nicht auf welcher Grundlage Sie eine Lösung _erwarten_ können, wir haben keinen SLA und dies ist kein Ticket-System.

Wüsste ich ad hoc eine Lösung, hätte ich sie geschrieben. Die entscheidende Zeile in der InnoSetup-Installation habe ich ja oben verlinkt. Da Sie sich anscheinend mit InnoSetup besser auskennen als meine Kollegen und ich, glaube ich der schnellste Weg wäre, einen Pull Request zu erstellen. Wir integrieren ihn gerne zum nächstmöglichen Release.

**Comment by SoftwareITEM** [comment]
Stimmt, warum sollte man von einer Softwareentwicklung eine Lösung für ein Software-Bug erwarten. 
Da wir aber für unsere Anwender die aktuelle Cryptomator-Version bereitstellen wollen und an einer Lösung interessiert sind, erstellen wir gerne ein Pull Request. Inhaltlich wird sich die Fehlerbeschreibung aber nicht ändern.
Danke

**Comment by SoftwareITEM** [comment]
Mir ist erst jetzt klar geworden, dass von uns die Lösung im Pull Request aufgenommen werden soll.
Die Lösung können wir nicht liefern, sondern nur das fehlerhafte Verhalten der Silent-Installation beschreiben.
Da wir aber keine Lösung erwarten dürfen, wird das Ticket geschlossen.

**Comment by tobihagemann** [comment]
Bevor hier weitere Missverständnisse entstehen: Es ist in Ordnung, dass dieser Fehler hier berichtet und auch getrackt wird. Bei einem Open-Source-Projekt gibt es trotzdem keine "Erwartungen". Wir müssten diesen Fehler erst einmal selber reproduzieren und analysieren, aber man kann diese Aussage über _alle_ Fehler treffen, daher werden kritische Fehler höher priorisiert. Der Vorteil an einem Open-Source-Projekt ist aber zusätzlich, dass im Prinzip _alle_ dazu befähigt werden, Fehler zu analysieren. Daher muss dieses Issue nicht geschlossen werden, falls der Fehler immer noch vorhanden ist.

**Comment by SoftwareITEM** [comment]
Hallo Tobias, deine sachliche Antwort auf meine "Erwartungs-Mail" wäre mir lieber. Ich habe einfach nur eine Reaktion "erwartet". Aber jetzt zum Wesentlichen:
Ich habe gestern auch noch mit dem Installer herumprobiert. Das Verhalten hat sich definitiv seit der 1.5.x geändert und lässt sich ganz einfach nachstellen: Beim Aufruf der Installations-EXE mit dem Parameter /COMPONENTS=main darf (nach der Bestätigung des Licence Agreements und des Installationspfades) nur die Cryptomator Komponente ausgewählt sein. Bei der 1.5.x wird aber auch der Dokan File System Driver ausgewählt. Genau das ist auch das eigentliche Problem . Bei unserer Silentinstallation poppt nach der Cryptomator Installation der Dokan Installationsdialog auf obwohl wir den gar nicht installieren wollen? Ich hoffe das hilft bei der Fehleranalyse weiter.

**Comment by SoftwareITEM** [comment]
![image](https://user-images.githubusercontent.com/65332614/87533215-8eb66900-c694-11ea-9570-863aaa425dc0.png)

**Comment by tobihagemann** [comment]
@infeo Ist es möglich, dass

https://github.com/cryptomator/cryptomator-win/blob/49ad465ba0cf4238174a383525eed4c1aa176ac9/resources/innosetup/setup.iss#L332-L346

dafür sorgt, dass der Haken einfach reinkommt, obwohl er nicht soll?

Ich habe mal die Components `main`, `dokan` und `webdav` ausprobiert und bei allen Variationen war "Dokan File System Driver" deaktiviert und ausgegraut mit dem Hinweis "Already Installed", daher komme ich auf diese Codezeilen.

**Comment by infeo** [comment]
A fix for this is in the pipeline, but it won't be included in the Cryptomator 1.5.7 release, but the next one.

**Comment by SoftwareITEM** [comment]
Hallo Cryptomator-Team,
leider ist der oben genannte Fehler auch in der 1.5.8 weiterhin da.
Sorry

**Comment by tobihagemann** [comment]
Das ist zu erwarten, weil der Fix noch nicht in den Installer von 1.5.8 eingeflossen ist. Wir mussten den 1.5.8 Hotfix-Release relativ zügig herausbringen, daher sind die Windows-Installerverbesserungen für 1.5.9 vorgesehen.

**Comment by SoftwareITEM** [comment]
Alles klar. 
Danke für die schnelle Rückmeldung.
