### ISSUE TITLE
Propt to reinstall / update Dokan appears after Cryptomator installation

### ISSUE THREAD

**Issue by BeyerMart** [cryptomator/cryptomator-win#32]
### Description
The installation of Cryptomator does not fail if a previous version of Dokan Libary is already installed.
The User is only notified while installing the new Dokan Libary, that there is an old version. Wich needs to be deinstalled (and rebooted) first. Appearing in branch [feature/dokanUpdate](https://github.com/cryptomator/cryptomator-win/tree/feature/dokanUpdate).
### Expected Behaviour
The installer checks, whether the user has the specified version of Dokan installed. If not it prompts the user to update it.

Installation:
![image](https://user-images.githubusercontent.com/37272740/86786058-cfdec580-c063-11ea-81c7-dfc8f8cda803.png)
After installation:
![image](https://user-images.githubusercontent.com/37272740/86786612-7d51d900-c064-11ea-928d-49d67abbea6a.png)

**Comment by infeo** [comment]
Will be fixed with merging the branch https://github.com/cryptomator/cryptomator-win/tree/feature/%2331-refactorDokanHandling

**Comment by infeo** [comment]
fixed with 999e97e1b0579b4548da0a9460e99444fd96f5bd
