### ISSUE TITLE
Sign binaries before packaging the installer

### ISSUE THREAD

**Issue by overheadhunter** [cryptomator/cryptomator-win#5]
Currently only the installer is signed. We want to sign every binary during installer creation.

**Comment by overheadhunter** [comment]
1. add to iss file:
```
[Setup]
SignTool=default sign /sha1 BAF9137F110811A5251BEB9BD6A929C2CC73E19C /tr http://timestamp.comodoca.com /v /fd sha256 $f
```

2. replace all javafx variables in the .iss file

3. change ant task inside pom.xml to only create the install dir:

```xml
<fx:deploy nativeBundles="image" ...>
```

4. add new ant task to:
    - copy files (`full-license.rtf`, `setup-icon.bmp`) to output dir
    - `cd` to output dir
    - invoke `iscc.exe foo.iss "/Sdefault=signtool $p"`

5. write rage post why Inno Setup forces the user to add the `/S` param...

**Comment by jasperweiss** [comment]
Can I just point out that installed binaries still aren't signed?

**Comment by overheadhunter** [comment]
We found out, that only the uninstaller got signed. We added code signing to Cryptomator.exe in Commit bfcb233 on 2017-11-29. One day after the release of 1.3.3. 🙈

Should be correct in the next version.
